# site settings
title: Claudia Kho
# subtitle: by HTML5 UP
email: claudkho@gmail.com
description: hi there!
# baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://khoclaudia.github.io/
author:
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url: https://github.com/khoclaudia
# gitlab_url: https://gitlab.com/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
# instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/khoclaudia
# pinterest_url:
# slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
